const n=(value:any)=>value==null?"unavailable":Number(value).toLocaleString(undefined,{maximumFractionDigits:4});
const titles:Record<string,string>={insider_transaction:"Insider transaction",institutional_holding:"Institutional holding",dividend:"Dividend",split:"Stock split",material_event:"Material SEC event",sector_kpi:"Industry metric"};

export default function ExtendedEvidence({documents=[],events=[],macro}:{documents?:any[],events?:any[],macro?:any}){
 return <>
 <details className="dashboardDetails"><summary>Original releases, transcripts and presentations</summary><div className="dashboardDetailsBody"><p className="muted">Archived source text retains its first observation. Publication time stays unavailable when the source does not establish it. The issuer registry and historical archive remain incomplete.</p>{documents.length?documents.map(doc=><article key={doc.id}><a href={doc.source_url} target="_blank" rel="noopener noreferrer">{doc.title}</a><p className="muted">{doc.kind.replaceAll("_"," ")} · published {doc.published_at||"time unavailable"} · first observed {doc.observed_at}{doc.truncated?" · stored text excerpt":""}</p></article>):<p className="muted">No original documents have been archived for this company yet.</p>}</div></details>
 <details className="dashboardDetails"><summary>Ownership and corporate events</summary><div className="dashboardDetailsBody"><p className="muted">Insider transaction codes distinguish purchases, sales, grants and option exercises. Institutional holdings are public provider observations; their original filings and historical availability have not been verified. Corporate-action history does not establish an upcoming event calendar.</p>{events.length?events.map(event=>{const p=event.payload||{};return <article key={event.id}><b>{titles[event.kind]||event.kind} · {event.event_date||"date unavailable"}</b><p>{event.kind==="institutional_holding"?`${p.holder} · ${n(p.shares)} shares · reported fraction held ${n(p.reported_fraction_held)}`:event.kind==="insider_transaction"?`${(p.owners||[]).map((o:any)=>o.name).join(", ")} · code ${p.transaction_code||"unavailable"} · ${n(p.shares)} shares · price ${n(p.price_per_share)} · ${p.derivative?"derivative security":"non-derivative security"}`:event.kind==="dividend"?`Provider amount ${n(p.amount)} · currency ${p.currency||"unavailable"}`:event.kind==="split"?`Split factor ${n(p.ratio)}:1`:p.headline||"Source evidence"}</p><a href={event.source_url} target="_blank" rel="noopener noreferrer">Source</a><small className="priceDate">{event.source} · first observed {event.observed_at}</small></article>}):<p className="muted">No structured ownership or corporate events have been collected yet.</p>}</div></details>
 <details className="dashboardDetails"><summary>Macro indicators and upcoming economic releases</summary><div className="dashboardDetailsBody"><p className="muted">Shared market context. Company-specific currency and commodity exposures are not mapped. Current CSV values include revisions and cannot be treated as values known in historical tests.</p>{macro?.series?.length?<div className="tableWrap"><table><thead><tr><th>Series</th><th>Value</th><th>Observation period</th><th>Version / first collection</th></tr></thead><tbody>{macro.series.map((s:any)=><tr key={s.series_id}><td><a href={s.source_url} target="_blank" rel="noopener noreferrer">{s.series_id}</a></td><td>{n(s.value)} · {s.units}</td><td>{s.observation_date}</td><td>{s.vintage_date?`ALFRED ${s.vintage_date}`:"Historical vintage unavailable"} · {s.observed_at}</td></tr>)}</tbody></table></div>:<p className="muted">Macro observations are unavailable.</p>}<p className="muted">{macro?.calendar_scope||"BLS calendar unavailable"} · last successful check {macro?.calendar_checked_at||"unavailable"}</p>{macro?.calendar?.map((event:any,i:number)=><p key={i}>{event.event_at} · <a href={event.source_url} target="_blank" rel="noopener noreferrer">{event.title}</a></p>)}</div></details>
 </>;
}
