import Link from "next/link";
import {getCandidates,getDataAudit,getSignals,getScorecard,getSystemHealth} from "@/lib/api";
import SearchBar from "./SearchBar";
import SetupTable from "./SetupTable";
import WeeklySignals from "./WeeklySignals";
export default async function Home(){
 const [candidates,audit,signals,scorecard,health]=await Promise.all([getCandidates(),getDataAudit(),getSignals(),getScorecard(),getSystemHealth()]);
 const withSetup=candidates.filter(x=>x.opportunity_score!=null); const avgN=withSetup.length?Math.round(withSetup.reduce((s,x)=>s+(x.setup_sample_size||0),0)/withSetup.length):0;
 return <main>
  <header><div><p className="eyebrow">S&amp;P 500 RESEARCH DESK</p><h1>StocksAnalyzer</h1><p className="sub">Current market data, filings, earnings and model validation, with coverage tracked separately.</p></div><span className="badge">DATA AUDIT · v0.3</span></header>
  <section className="panel"><div className="panelHead"><div><p className="eyebrow">SYSTEM HEALTH</p><h2>{health.status==="success"?"✓ Data update validated":health.status==="error"?"⚠ Data update failed":"Data update status"}</h2></div><span className="badge">{health.status==="success"?"HEALTHY":health.status==="error"?"ERROR":"CHECKING"}</span></div><div className="definitions"><div><b>Latest market data</b><span>{health.latest_price_date||"—"}</span></div><div><b>Latest features</b><span>{health.latest_feature_date||"—"}</span></div><div><b>Last automated run</b><span>{health.last_run?.finished_at||health.last_run?.started_at||"No recorded run yet"}</span></div><div><b>Research sources checked</b><span>{health.research_sources_run?.finished_at||health.research_sources_run?.started_at||"Not refreshed yet"}</span></div><div><b>Fundamentals coverage</b><span>{health.coverage?`${health.coverage.fundamentals} / ${health.coverage.universe}`:"—"}</span></div><div><b>Earnings coverage</b><span>{health.coverage?`${health.coverage.earnings} / ${health.coverage.universe}`:"—"}</span></div><div><b>Predictive model</b><span>{health.model_validation?.validated_horizons?.length>=2?`${health.model_validation.best_stage} · ${health.model_validation.validated_horizons.join("/")}d validated`:health.model_validation?.status==="error"?"Validation error":health.model_validation?.status==="success"?"Validation completed · no model promoted":"Validation pending · heuristic ranking"}</span></div></div>{health.last_run?.error_message&&<p className="muted">Error: {health.last_run.error_message}</p>}{health.research_sources_run?.error_message&&<p className="muted">Research source error: {health.research_sources_run.error_message}</p>}{health.model_validation?.error_message&&<p className="muted">Model validation error: {health.model_validation.error_message}</p>}</section>
  <SearchBar stocks={candidates.map(x=>({ticker:x.ticker,company:x.company,sector:x.sector}))}/>
  <section className="grid"><article><span>Universe</span><strong>{audit.universe||"—"}</strong><small>S&amp;P 500 constituents synced</small></article><article><span>Setup rows</span><strong>{withSetup.length||"—"}</strong><small>latest research snapshots returned by API</small></article><article><span>Avg. similar samples</span><strong>{avgN||"—"}</strong><small>historical observations behind current setup metric</small></article></section>
  <WeeklySignals signals={signals} scorecard={scorecard}/>
  <section className="panel explainer"><p className="eyebrow">WHAT THE NUMBERS MEAN</p><h2>Current calculations</h2><div className="definitions"><div><b>Research rank</b><span>Research-priority ordering combining the descriptive setup score with a bounded latest-earnings catalyst adjustment.</span></div><div><b>Latest earnings catalyst</b><span>EPS and revenue surprise from a report published before the signal close and within the prior 30 days.</span></div><div><b>Opportunity score</b><span>Heuristic 0–100 score using historical setup hit-rate, median 5-day return, upside to the 60-day high and sample size.</span></div><div><b>Historical up rate</b><span>Among past price setups similar to today&apos;s, the share with a positive forward 5-day return.</span></div><div><b>Median 5d</b><span>Median forward 5-trading-day return of historically similar setups.</span></div><div><b>Upside to 60d high</b><span>Distance from current price to the recent 60-trading-day high; reference headroom, not a price target.</span></div><div><b>Drawdown 60d</b><span>How far the current close sits below its 60-day high.</span></div><div><b>Fundamentals / valuation / earnings</b><span>Partial research factors where source data exists.</span></div></div></section>
  <section className="panel"><div className="panelHead"><div><p className="eyebrow">CURRENT DATA</p><h2>Latest setup screen</h2></div><p className="muted">Sorted by research priority: setup + bounded latest-earnings catalyst · descriptive only</p></div>{candidates.length?<SetupTable rows={candidates}/>:<p className="muted">Backend unavailable. Start FastAPI on port 8000.</p>}</section>
  <section className="panel"><div className="panelHead"><div><p className="eyebrow">COVERAGE AUDIT</p><h2>What data do we actually have?</h2></div><p className="muted">{audit.universe} companies in current universe</p></div><div className="coverageGrid">{audit.layers.map(x=><div className="coverageCard" key={x.key}><div><b>{x.label}</b><span>{x.companies} / {x.total} companies</span></div><strong>{x.coverage_pct.toFixed(1)}%</strong><progress max="100" value={x.coverage_pct}/></div>)}</div>{audit.missing_price_tickers.length>0&&<p className="muted">Missing price history: <b>{audit.missing_price_tickers.join(", ")}</b></p>}<p className="muted">Coverage means at least one record per company. It does not establish complete TTM cash flow, fresh estimates or predictive value.</p></section>
  <section className="panel explainer"><p className="eyebrow">DATA INVENTORY</p><h2>What is already stored</h2><div className="definitions"><div><b>Daily prices</b><span>OHLCV history, primarily Twelve Data.</span></div><div><b>Price features</b><span>Momentum, volatility, volume, drawdown, support, rebound and relative-market features.</span></div><div><b>Forward labels</b><span>Historical forward 5-day return and direction label used for research/backtesting.</span></div><div><b>Fundamentals</b><span>Financial statement metrics where available.</span></div><div><b>Valuation</b><span>P/E, price-to-FCF, FCF yield and market cap where available.</span></div><div><b>Earnings events</b><span>Historical earnings actual vs consensus used as catalyst evidence.</span></div></div></section>
 </main>;
}
