import Link from "next/link"; import {getCandidates,getDataAudit} from "@/lib/api"; import SearchBar from "./SearchBar";
const pct=(v:number|null,d=1)=>v==null?"—":`${(v*100).toFixed(d)}%`; const num=(v:number|null,d=1)=>v==null?"—":v.toFixed(d);
const tips={
 ticker:"Ticker — The stock's exchange trading symbol.",
 company:"Company — The company's official name.",
 sector:"Sector — The company's primary business sector.",
 price:"Current Price — The latest closing price stored in price_history. This is the latest market close in our database, not a live quote.",
 date:"Data Date — The trading date of the displayed closing price. Setup calculations have their own as-of date and should normally align with the latest trading day.",
 opportunity:"Opportunity Score (0–100) — Current heuristic score: 50% historical up-rate component, 30% median 5-day return component, and 20% upside-to-60-day-high component after normalization, multiplied by an evidence factor based on sample size (full weight around 100 samples). Walk-forward validation did not show useful predictive lift, so this is descriptive, not a forecast or recommendation.",
 up:"Historical Up Rate — Among historical observations with a price setup similar to today's, the percentage followed by a positive 5-trading-day return. Similarity uses 60-day drawdown and distance to 60-day support, each within roughly 4 percentage points of today's values. This is a historical frequency, not a calibrated probability forecast.",
 median:"Median 5d — Median forward 5-trading-day return across the historically similar setups. The median reduces the influence of extreme moves. For example, 2% means half of the observations finished above 2% and half below.",
 high:"To 60d High — Percentage distance from the current close to the highest price in the previous 60 trading days. It is reference headroom only: 15% means roughly a 15% rise would be required to revisit that high. It is not a price target.",
 drawdown:"60d Drawdown — Current close relative to the 60-trading-day high. A more negative value means the stock is trading further below its recent high.",
 samples:"Samples — Number of historical observations considered similar to the current setup for which a forward 5-day return is known. More samples provide a broader evidence base, but do not guarantee predictive value."
};
const TH=({label,tip}:{label:string,tip:string})=><th className="tipHead"><span tabIndex={0}>{label}<i>?</i><b className="tooltip">{tip}</b></span></th>;
export default async function Home(){const [candidates,audit]=await Promise.all([getCandidates(),getDataAudit()]); const withSetup=candidates.filter(x=>x.opportunity_score!=null); const avgN=withSetup.length?Math.round(withSetup.reduce((s,x)=>s+(x.setup_sample_size||0),0)/withSetup.length):0;
return <main><header><div><p className="eyebrow">S&P 500 RESEARCH DESK</p><h1>StocksAnalyzer</h1><p className="sub">What we have today — prices, technical setup history and partial fundamental/earnings coverage.</p></div><span className="badge">DATA AUDIT · v0.3</span></header>
<SearchBar stocks={candidates.map(x=>({ticker:x.ticker,company:x.company,sector:x.sector}))}/><section className="grid"><article><span>Universe</span><strong>503</strong><small>S&P 500 constituents synced</small></article><article><span>Setup rows</span><strong>{withSetup.length||"—"}</strong><small>latest research snapshots returned by API</small></article><article><span>Avg. similar samples</span><strong>{avgN||"—"}</strong><small>historical observations behind current setup metric</small></article></section>
<section className="panel explainer"><p className="eyebrow">WHAT THE NUMBERS MEAN</p><h2>Current calculations</h2><div className="definitions"><div><b>Opportunity score</b><span>Heuristic 0–100 score using historical setup hit-rate, median 5-day return, upside to the 60-day high and sample size. Our walk-forward test did not show useful out-of-sample lift, so treat it as descriptive — not a validated forecast.</span></div><div><b>Historical up rate</b><span>Among past price setups similar to today's drawdown/support position, the share with a positive forward 5-day return. It is not a calibrated probability forecast.</span></div><div><b>Median 5d</b><span>Median forward 5-trading-day return of those historically similar setups.</span></div><div><b>Upside to 60d high</b><span>Distance from current price to the recent 60-trading-day high; this is reference headroom, not a price target.</span></div><div><b>Drawdown 60d</b><span>How far the current close sits below its 60-day high.</span></div><div><b>Fundamentals / valuation / earnings</b><span>Partial research factors where source data exists. Coverage is not yet complete across the full index.</span></div></div></section>
<section className="panel"><div className="panelHead"><div><p className="eyebrow">CURRENT DATA</p><h2>Latest setup screen</h2></div><p className="muted">Sorted by existing heuristic opportunity score · descriptive only</p></div>
{candidates.length?<table><thead><tr><TH label="Ticker" tip={tips.ticker}/><TH label="Company" tip={tips.company}/><TH label="Sector" tip={tips.sector}/><TH label="Current price" tip={tips.price}/><TH label="Data date" tip={tips.date}/><TH label="Opportunity" tip={tips.opportunity}/><TH label="Hist. up rate" tip={tips.up}/><TH label="Median 5d" tip={tips.median}/><TH label="To 60d high" tip={tips.high}/><TH label="60d drawdown" tip={tips.drawdown}/><TH label="Samples" tip={tips.samples}/></tr></thead><tbody>{candidates.map(x=><tr key={x.ticker}><td><Link className="ticker" href={`/company/${x.ticker}`}>{x.ticker}</Link></td><td>{x.company}</td><td>{x.sector||"—"}</td><td>{x.current_price==null?"—":`${Number(x.current_price).toFixed(2)}`}</td><td>{x.price_date||x.as_of_date||"—"}</td><td>{num(x.opportunity_score)}</td><td>{pct(x.setup_probability_up)}</td><td>{pct(x.setup_median_return_5d)}</td><td>{pct(x.upside_to_60d_high)}</td><td>{pct(x.setup_drawdown_60d)}</td><td>{x.setup_sample_size??"—"}</td></tr>)}</tbody></table>:<p className="muted">Backend unavailable. Start FastAPI on port 8000.</p>}</section>
<section className="panel"><div className="panelHead"><div><p className="eyebrow">COVERAGE AUDIT</p><h2>What data do we actually have?</h2></div><p className="muted">{audit.universe} companies in current universe</p></div><div className="coverageGrid">{audit.layers.map(x=><div className="coverageCard" key={x.key}><div><b>{x.label}</b><span>{x.companies} / {x.total} companies</span></div><strong>{x.coverage_pct.toFixed(1)}%</strong><progress max="100" value={x.coverage_pct}/></div>)}</div>{audit.missing_price_tickers.length>0&&<p className="muted">Missing price history: <b>{audit.missing_price_tickers.join(", ")}</b></p>}<p className="muted">This audit measures company coverage, not data quality or predictive value. A layer can have high coverage and still require validation.</p></section><section className="panel explainer"><p className="eyebrow">DATA INVENTORY</p><h2>What is already stored</h2><div className="definitions"><div><b>Daily prices</b><span>OHLCV history, primarily Twelve Data, with roughly six years for the broad universe.</span></div><div><b>Price features</b><span>1d/5d/20d momentum, 20d volatility, volume ratio, SMA20 distance, 20d/60d drawdown, support distance, rebound potential, SPY market momentum/volatility and relative momentum.</span></div><div><b>Forward labels</b><span>Historical forward 5-day return and positive/negative label used only for research/backtesting.</span></div><div><b>Fundamentals</b><span>Revenue, operating income, net income, diluted EPS, free cash flow, cash/debt and derived growth/margin/leverage metrics where available.</span></div><div><b>Valuation</b><span>P/E, price-to-FCF, FCF yield and market cap where available.</span></div><div><b>Earnings events</b><span>Alpha Vantage EPS actual vs estimate history has started ingesting; only partial universe coverage so far.</span></div></div></section></main>}